### ISSUE TITLE
Client not recognizing game

### ISSUE THREAD

**Issue by kepl3r22b** [colinhartigan/valorant-inventory-manager#10]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 894, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\client_management\client.py", line 34, in connect
  File "src\client_management\client.py", line 71, in autodetect_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?

I'm a bit curious as to why the client is recognizing the game. Is it because I might've installed it in the wrong folder? I have the game open in windowed full screen and I've tried opening the game before using the client

**Comment by colinhartigan** [comment]
this is an odd one - try closing the game, deleting `%APPDATA%/valorant-inventory-manager`, then opening the game and VIM

**Comment by colinhartigan** [comment]
odd. not sure what's causing it
