### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kami3va** [colinhartigan/valorant-inventory-manager#11]
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1028, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0795' in position 59: character maps to <undefined>
Call stack:
  File "main.py", line 14, in <module>
  File "src\server.py", line 79, in start
  File "asyncio\base_events.py", line 566, in run_until_complete
  File "asyncio\base_events.py", line 534, in run_forever
  File "asyncio\base_events.py", line 1771, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "websockets\legacy\protocol.py", line 1245, in keepalive_ping
  File "websockets\legacy\protocol.py", line 846, in ping
  File "websockets\legacy\protocol.py", line 1187, in write_frame
  File "websockets\legacy\protocol.py", line 1157, in write_frame_sync
  File "logging\__init__.py", line 1719, in debug
  File "logging\__init__.py", line 1763, in log
  File "logging\__init__.py", line 1444, in log
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "logging\__init__.py", line 1127, in emit
  File "logging\__init__.py", line 1033, in emit
Message: '> %s'
Arguments: (Frame(fin=True, opcode=<Opcode.PING: 9>, data=b'\xde\x95J\r', rsv1=False, rsv2=False, rsv3=False),)
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1028, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0795' in position 59: character maps to <undefined>
Call stack:
  File "main.py", line 14, in <module>
  File "src\server.py", line 79, in start
  File "asyncio\base_events.py", line 566, in run_until_complete
  File "asyncio\base_events.py", line 534, in run_forever
  File "asyncio\base_events.py", line 1771, in _run_once
  File "asyncio\events.py", line 88, in _run
  File "websockets\legacy\protocol.py", line 944, in transfer_data
  File "websockets\legacy\protocol.py", line 1013, in read_message
  File "websockets\legacy\protocol.py", line 1089, in read_data_frame
  File "websockets\legacy\protocol.py", line 1151, in read_frame
  File "logging\__init__.py", line 1719, in debug
  File "logging\__init__.py", line 1763, in log
  File "logging\__init__.py", line 1444, in log
  File "logging\__init__.py", line 1514, in _log
  File "logging\__init__.py", line 1524, in handle
  File "logging\__init__.py", line 1586, in callHandlers
  File "logging\__init__.py", line 894, in handle
  File "logging\__init__.py", line 1127, in emit
  File "logging\__init__.py", line 1033, in emit
Message: '< %s'
Arguments: (Frame(fin=True, opcode=<Opcode.PONG: 10>, data=b'\xde\x95J\r', rsv1=False, rsv2=False, rsv3=False),)

Here is the code I dont understand anything so :D

**Comment by colinhartigan** [comment]
you can ignore this, it's just a weird bug from the logging library im using and doesn't impact the functionality of VIM
