### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by muhammadnazmul** [colinhartigan/valorant-inventory-manager#12]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-02-11 11:19:33,104 [ERROR] VIM_errors: ----- EXCEPTION -----
2022-02-11 11:19:33,105 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\server.py", line 123, in ws_entrypoint
  File "src\client_management\client.py", line 99, in fetch_loadout
AttributeError: 'NoneType' object has no attribute 'fetch_player_loadout'

**Comment by bickey647** [comment]
i have also encountered same error 
is the solutio n available here?

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b2
