### ISSUE TITLE
eror '7e17a92f-6ba7-5b01-892d-120077a55878'

### ISSUE THREAD

**Issue by toroclown** [colinhartigan/valorant-inventory-manager#14]
2022-02-11 13:59:15,623 [ERROR] VIM_errors: error: please create an issue with the traceback below if this problem persists
2022-02-11 13:59:15,625 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\inventory_management\file_manager.py", line 42, in fetch_individual_inventory
KeyError: '7e17a92f-6ba7-5b01-892d-120077a55878'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '7e17a92f-6ba7-5b01-892d-120077a55878'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '7e17a92f-6ba7-5b01-892d-120077a55878'

press enter to exit...

help please

**Comment by colinhartigan** [comment]
assuming this is the same issue as https://github.com/colinhartigan/valorant-inventory-manager/issues/7 (different region than NA), closing b/c duplicate
