### ISSUE TITLE
KeyError: '95964136-da72-5bf3-ae03-19992ef2a19b'

### ISSUE THREAD

**Issue by minhnq62** [colinhartigan/valorant-inventory-manager#18]
2022-02-11 17:49:22,759 [ERROR] VIM_errors: error: please create an issue with the traceback below if this problem persists
2022-02-11 17:49:22,760 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\inventory_management\file_manager.py", line 42, in fetch_individual_inventory
KeyError: '95964136-da72-5bf3-ae03-19992ef2a19b'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '95964136-da72-5bf3-ae03-19992ef2a19b'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '95964136-da72-5bf3-ae03-19992ef2a19b'

Can anybody help me :((

**Comment by colinhartigan** [comment]
assuming this is the same issue as https://github.com/colinhartigan/valorant-inventory-manager/issues/7 (different region than NA), closing b/c duplicate

**Comment by minhnq62** [comment]
> assuming this is the same issue as #7 (different region than NA), closing b/c duplicate

so you mean that I must be in a NA region to use this?
