### ISSUE TITLE
Connection failed Couldn't connect to your computer. Is the VIM client companion running?

### ISSUE THREAD

**Issue by smwlks** [colinhartigan/valorant-inventory-manager#27]
2022-02-12 21:22:48,751 [ERROR] VIM_errors: ----- EXCEPTION -----
2022-02-12 21:22:48,752 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\server.py", line 123, in ws_entrypoint
  File "src\client_management\client.py", line 165, in fetch_loadout
KeyError: '65baa0cd-42ec-f99d-54a0-338d795b5824'

VIM failed to connect, please fix it quickly

**Comment by smwlks** [comment]
답을 남겨

**Comment by smwlks** [comment]
What is the problem with this key please solve it I really want the skins hahaha

**Comment by smwlks** [comment]
Teach me how to fix this dog fucking bug Do you know how much time I wasted on you? fucking

**Comment by SkyFlouz** [comment]
Same problem, i need help too

**Comment by smwlks** [comment]
I'm going to kill you. You dare waste my time like this? you are dead

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b2

**Comment by recur74** [comment]
@smwlks Your comments are unacceptable. Please crawl away from here.
@colinhartigan Keep up the good work!
