### ISSUE TITLE
VIM error key : c6c2bc3e-5010-5b7a-a6fc-2cd1ff0d2b4a

### ISSUE THREAD

**Issue by Haianh0706** [colinhartigan/valorant-inventory-manager#33]
_   ________  ___
 | | / /  _/  |/  /
 | |/ // // /|_/ /
 |___/___/_/  /_/ v1.0.0b1

2022-02-20 12:20:15,639 [ERROR] VIM_errors: error: please create an issue with the traceback below if this problem persists
2022-02-20 12:20:15,640 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\inventory_management\file_manager.py", line 42, in fetch_individual_inventory
KeyError: 'c6c2bc3e-5010-5b7a-a6fc-2cd1ff0d2b4a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: 'c6c2bc3e-5010-5b7a-a6fc-2cd1ff0d2b4a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: 'c6c2bc3e-5010-5b7a-a6fc-2cd1ff0d2b4a'

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b2
