### ISSUE TITLE
Crash error - VIM Server

### ISSUE THREAD

**Issue by LarsenWood** [colinhartigan/valorant-inventory-manager#38]
2022-03-01 20:38:04,742 [ERROR] VIM_errors: Traceback (most recent call last):
  File "main.py", line 16, in <module>
  File "src\server.py", line 86, in start
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "src\session_management\client_state.py", line 77, in loop
  File "src\session_management\client_state.py", line 32, in randomizer_check
TypeError: 'NoneType' object is not subscriptable

This crashed my VIM Server

**Comment by colinhartigan** [comment]
make sure valorant is alraedy running before opening VIM
