### ISSUE TITLE
Error occured 

### ISSUE THREAD

**Issue by Thunder2703** [colinhartigan/valorant-inventory-manager#65]
_   _____   __   ____  ___  ___   _  ________        __    _              ___
| | / / _ | / /  / __ \/ _ \/ _ | / |/ /_  __/______ / /__ (_)__  ________/ (_)
| |/ / __ |/ /__/ /_/ / , _/ __ |/    / / / /___(_-</  '_// / _ \/___/ __/ / /
|___/_/ |_/____/\____/_/|_/_/ |_/_/|_/ /_/     /___/_/\_\/_/_//_/    \__/_/_/v1.2.3

the program encountered an error; please create an issue with the traceback below if this problem persists
Traceback (most recent call last):
  File "src\utility\onboarding.py", line 22, in __init__
  File "valclient\client.py", line 60, in __init__
ValueError: Invalid region, valid regions are: ['na', 'eu', 'latam', 'br', 'ap', 'kr', 'pbe']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 886, in __get_lockfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Riot Games\\Riot Client\\Config\\lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "valclient\client.py", line 73, in activate
  File "valclient\client.py", line 891, in __get_lockfile
valclient.exceptions.LockfileError: Lockfile not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "src\startup.py", line 35, in run
  File "src\utility\onboarding.py", line 24, in __init__
  File "src\utility\onboarding.py", line 84, in autodetect_region
  File "valclient\client.py", line 82, in activate
valclient.exceptions.HandshakeError: Unable to activate; is VALORANT running?
press enter to exit...

**Comment by Thunder2703** [comment]
idk what to do and why this happen

**Comment by qualk** [comment]
Hmm, have you started Valorant before?

**Comment by qualk** [comment]
@Thunder2703, you have to open it while Riot Client or Valorant is open. 

The reason is that VIM checks if there is a lockfile for Riot Client/Valorant to see if it is open, in your case, neither of them are open.
