### ISSUE TITLE
VIM ERROR 233bfd10-0cf2-5bbe-b796-9c5e61f64034'

### ISSUE THREAD

**Issue by UNCHEESABLE** [colinhartigan/valorant-inventory-manager#7]
_   ________  ___
 | | / /  _/  |/  /
 | |/ // // /|_/ /
 |___/___/_/  /_/ v1.0.0b1

2022-02-11 08:49:05,220 [ERROR] VIM_errors: error: please create an issue with the traceback below if this problem persists
2022-02-11 08:49:05,222 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\inventory_management\file_manager.py", line 42, in fetch_individual_inventory
KeyError: '233bfd10-0cf2-5bbe-b796-9c5e61f64034'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '233bfd10-0cf2-5bbe-b796-9c5e61f64034'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '233bfd10-0cf2-5bbe-b796-9c5e61f64034'

press enter to exit...

this showing in vim.exe

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b2
