### ISSUE TITLE
Happens every time I try to run

### ISSUE THREAD

**Issue by wespd** [colinhartigan/valorant-inventory-manager#8]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '1b33dc2a-4d72-5dac-bc47-f8479bbaf006'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '1b33dc2a-4d72-5dac-bc47-f8479bbaf006'

**Comment by colinhartigan** [comment]
looking into this and should have a fix soon

**Comment by colinhartigan** [comment]
assuming this is the same issue as https://github.com/colinhartigan/valorant-inventory-manager/issues/7 (different region than NA), closing b/c duplicate
